plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.privilege.mobile'
    compileSdk 33

    defaultConfig {
        applicationId "ru.privilege.mobile"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
